#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Attack Tree: nodes, UCT selection, backpropagation.

Each AttackNode represents one attack strategy (prompt).
The tree captures the genealogy of how strategies evolved from each other.
MCTS-style UCT balances exploitation (high-reward nodes) with exploration
(under-visited nodes).
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# AttackNode
# ---------------------------------------------------------------------------

@dataclass
class AttackNode:
    """
    A node in the attack tree.

    Attributes
    ----------
    prompt      : the attack prompt string at this node
    goal        : the underlying harmful goal being tested
    parent      : parent node (None for root)
    children    : child nodes generated by evolution operators
    visit_count : number of times this node was evaluated
    total_reward: cumulative reward from all evaluations
    operator    : the operator that generated this node
    depth       : depth in the tree (root = 0)
    meta        : arbitrary extra metadata
    """
    prompt: str
    goal: str
    parent: Optional["AttackNode"] = field(default=None, repr=False)
    children: List["AttackNode"] = field(default_factory=list, repr=False)

    visit_count: int = 0
    total_reward: float = 0.0
    best_reward: float = 0.0

    operator: str = "seed"
    depth: int = 0
    meta: Dict[str, Any] = field(default_factory=dict)

    # Populated after evaluation
    last_transcript: List[Dict[str, str]] = field(default_factory=list, repr=False)
    last_label: str = "not_evaluated"   # affirmative / refusal / unclear / not_evaluated

    @property
    def avg_reward(self) -> float:
        return self.total_reward / self.visit_count if self.visit_count > 0 else 0.0

    @property
    def is_leaf(self) -> bool:
        return len(self.children) == 0

    @property
    def is_success(self) -> bool:
        return self.best_reward >= 0.8

    def uct_score(self, parent_visits: int, exploration_c: float = 1.414) -> float:
        """Upper Confidence Bound for Trees (UCT-1)."""
        if self.visit_count == 0:
            return float("inf")
        exploit = self.avg_reward
        explore = exploration_c * math.sqrt(math.log(parent_visits + 1) / self.visit_count)
        return exploit + explore

    def to_dict(self) -> Dict[str, Any]:
        return {
            "prompt": self.prompt,
            "goal": self.goal,
            "operator": self.operator,
            "depth": self.depth,
            "visit_count": self.visit_count,
            "avg_reward": round(self.avg_reward, 4),
            "best_reward": round(self.best_reward, 4),
            "last_label": self.last_label,
            "meta": self.meta,
        }


# ---------------------------------------------------------------------------
# AttackTree
# ---------------------------------------------------------------------------

class AttackTree:
    """
    Manages the collection of nodes for one goal.
    Provides UCT-based selection and tree statistics.
    """

    def __init__(self, goal: str, seed_prompts: List[str]):
        self.goal = goal
        # Root is a virtual node; seed prompts are its children
        self.root = AttackNode(
            prompt="[ROOT]",
            goal=goal,
            operator="root",
            depth=0,
        )
        for sp in seed_prompts:
            child = AttackNode(
                prompt=sp,
                goal=goal,
                parent=self.root,
                operator="seed",
                depth=1,
            )
            self.root.children.append(child)

        self.all_nodes: List[AttackNode] = list(self.root.children)

    def select(self, exploration_c: float = 1.414) -> AttackNode:
        """
        UCT tree walk: from root, always descend to the child with the
        highest UCT score. Stop at a leaf or an unvisited node.
        """
        node = self.root
        while not node.is_leaf:
            # Among children, pick the one with highest UCT score
            parent_visits = max(node.visit_count, 1)
            best = max(
                node.children,
                key=lambda c: c.uct_score(parent_visits, exploration_c),
            )
            if best.visit_count == 0:
                # Unvisited — evaluate it
                return best
            node = best
        return node

    def add_child(self, parent: AttackNode, prompt: str, operator: str, meta: Optional[Dict] = None) -> AttackNode:
        child = AttackNode(
            prompt=prompt,
            goal=self.goal,
            parent=parent,
            operator=operator,
            depth=parent.depth + 1,
            meta=meta or {},
        )
        parent.children.append(child)
        self.all_nodes.append(child)
        return child

    def backpropagate(self, node: AttackNode, reward: float) -> None:
        """Walk from node up to root, updating visit counts and rewards."""
        cur: Optional[AttackNode] = node
        while cur is not None and cur is not self.root:
            cur.visit_count += 1
            cur.total_reward += reward
            if reward > cur.best_reward:
                cur.best_reward = reward
            cur = cur.parent
        # Also update root visit count for UCT denominator
        self.root.visit_count += 1

    def best_nodes(self, top_k: int = 5) -> List[AttackNode]:
        """Return top-k nodes by best_reward."""
        return sorted(
            [n for n in self.all_nodes if n.visit_count > 0],
            key=lambda n: n.best_reward,
            reverse=True,
        )[:top_k]

    def stats(self) -> Dict[str, Any]:
        visited = [n for n in self.all_nodes if n.visit_count > 0]
        successes = [n for n in visited if n.is_success]
        return {
            "goal": self.goal,
            "total_nodes": len(self.all_nodes),
            "visited_nodes": len(visited),
            "success_nodes": len(successes),
            "best_reward": max((n.best_reward for n in visited), default=0.0),
        }
